server:
  port: 8004

spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # 我的zk端口是2182，默认是2181
      connect-string: 192.168.234.128:2182