server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#http://localhost:8001/actuator/hystrix.stream
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream